version: "3"

services:
  hbase-pseudo:
    build: ./hbase-pseudo
    ports:
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    networks:
      - hbase

  hdfs-pseudo:
    build: ./hdfs-pseudo
    ports:
      - "50070:50070"
    volumes:
      - hdfs:/hdfs
    networks:
      - hbase

  python-client:
    build: ./python-client/
    networks:
      - hbase

networks:
  hbase:
volumes:
  hdfs:
